Update best-practices.md
Azure/data-api-builder pull request #1411
Opened 2023-04-05 04:24 UTC by abhi1358

## Why make this change?

- Improving the doc

## What is this change?

- Doc update

2023-04-05 14:30 UTC, seantleonard approved these changes
Thank you for your contribution 👍

2023-04-05 21:54 UTC, Aniruddh25 commented on docs/best-practices.md
> +- Stored Procedures
If the entity is backed by a stored procedure, both query or mutation would be named:
 - `executeCompositeNameEntity`

2023-04-07 21:32 UTC, seantleonard requested changes
@abhi1358 , I believe other local changes made it into this PR for ignoring some nuget warnings and changing the package url. Those should be moved to separate PRs where not already created.

2023-04-07 21:32 UTC, seantleonard commented on docs/best-practices.md
> +- If the entity is backed by a stored procedure, both query or mutation would be named:
```suggestion
- If the entity is backed by a stored procedure, the generated query or mutation would be named:
```
nit: more explicit details.

2023-04-19 05:40 UTC, abhishekkumams commented
/azp run

2023-04-24 05:06 UTC, abhishekkumams commented
/azp run

2023-04-24 17:27 UTC, abhishekkumams commented
/azp run

2023-04-24 17:38 UTC, abhishekkumams approved these changes

2023-04-24 17:50 UTC, merged