Health Endpoint Design Document
Azure/data-api-builder pull request #2503
Opened 2024-12-30 05:41 UTC by sezal98

## Why make this change?

Design DOcument for Health Endpoint

## What is this change?

- Summary of how your changes work to give reviewers context of your intent.
  - Links to relevant documentation / StackOverflow, if applicable.

## How was this tested?

- [ ] Integration Tests
- [ ] Unit Tests

## Sample Request(s)

- Example REST and/or GraphQL request to demonstrate modifications
- Example of CLI usage to demonstrate modifications

2025-01-02 03:51 UTC, abhishekkumams commented on docs/design/HealthEndpoint.md
> +The objective of this task is to enhance the "Health Endpoint" for DAB. Currently we only show whether the DAB Engine is healthy or not and which version of DAB is running. However, the objective und
to support each endpoint? do you mean for each entity?

2025-01-03 03:38 UTC, abhishekkumams commented
How would the health endpoint will function with hot reload? In case of bad config it might use last good known config which might give wrong status.

Would be good to add limitations.

2025-01-03 04:59 UTC, sezal98 commented
> How would the health endpoint will function with hot reload? In case of bad config it might use last good known config which might give wrong status.
> 
> Would be good to add limitations.
I dont see an issue in this, If DAB Engine is working then health point should be consistent with that. If DAB engine is using the last known config, then health endpoint would also show the health of the last known config. 
Showing health of the current config but running the engine with the last known config would create inconsistencies which would be incorrect for the user. 
We should put this in documentation that we are using the last known config in case of hot reload and showing health of that old config not the bad config.

Another important point to note is.. Health is independent of Validity of config. Health endpoint is only shown when the config is valid (no errors) and DAB engine is running. So the case of bad config would not occur. 


@JerryNixon , Any thoughts on this?

2025-01-03 05:01 UTC, sezal98 commented on docs/design/HealthEndpoint.md
> +The objective of this task is to enhance the "Health Endpoint" for DAB. Currently we only show whether the DAB Engine is healthy or not and which version of DAB is running. However, the objective und
Endpoint here refers to both entity and datasource as we need to show the health of both of these endpoints. Updating to clearly state the same in document

2025-01-03 13:18 UTC, abhishekkumams commented on docs/design/HealthEndpoint.md
> +      "moniker": "sqlserver", (optional default: NULL) // not required, on purpose, most have just one
what is `moniker`?

2025-01-03 13:25 UTC, abhishekkumams commented
> > How would the health endpoint will function with hot reload? In case of bad config it might use last good known config which might give wrong status.
> > Would be good to add limitations.
> 
> I dont see an issue in this, If DAB Engine is working then health point should be consistent with that. If DAB engine is using the last known config, then health endpoint would also show the health of the last known config. Showing health of the current config but running the engine with the last known config would create inconsistencies which would be incorrect for the user. We should put this in documentation that we are using the last known config in case of hot reload and showing health of that old config not the bad config.
> 
> Another important point to note is.. Health is independent of Validity of config. Health endpoint is only shown when the config is valid (no errors) and DAB engine is running. So the case of bad config would not occur.
> 
> @JerryNixon , Any thoughts on this?

Thanks for clarifying. can you add the same to your documentation as well.

2025-01-05 11:02 UTC, sezal98 commented on docs/design/HealthEndpoint.md
> +    "<entity-name>": {
If there is a configuration issue, and the engine has not started.. then the health endpoint will also not be displayed. Health is displayed when the engine is started and we are able to hit localhost:500. This endpoint would contain information of each entity .. this information signifies whether basic query like `get all` is running smoothly and under the threshold timelimit or not. I dont see any issue in case entity is ill configured, but lets discuss more in detail

2025-01-06 17:22 UTC, abhishekkumams commented
How will we be checking if an endpoint is healthy or not? Are we gonna make a db call internally? Or hit the endpoint itself to check the status? Or something else?

2025-01-07 07:25 UTC, abhishekkumams commented on docs/design/HealthEndpoint.md
> +    "<entity-name>": {
what about db issues? are we assuming that if the engine is started all the endpoints would be healthy? if not, how will we be knowing status of each endpoint?

2025-01-09 07:12 UTC, sezal98 commented on docs/design/HealthEndpoint.md
> +    "<entity-name>": {
No, Health is checked only when the user tries to access the health endpoint. Hence, only when he hits the endpoint the queries are called. 
In case there are db issues, the health would be "unhealthy"

2025-01-09 07:13 UTC, sezal98 commented
> How will we be checking if an endpoint is healthy or not? Are we gonna make a db call internally? Or hit the endpoint itself to check the status? Or something else?

Yes, as mentioned in the document, we would be making the call internally and hitting the specified query. If this query is sucessfull and within the threshold specified, the entity would be considered healthy. Else, we would say, its unhealthy with the exception message

2025-01-09 20:16 UTC, RubenCerna2079 commented on docs/design/HealthEndpoint.md
> +The Entity config parameters contain information about the GET filter or query which needs to be carried out on the data source entiy and under what threshold should the response be received for it t
Should be `entity`
```suggestion
The Entity config parameters contain information about the GET filter or query which needs to be carried out on the data source entity and under what threshold should the response be received for it to qualify as a healthy entity.
```

2025-01-09 20:16 UTC, RubenCerna2079 commented on docs/design/HealthEndpoint.md
> +
Should be `detailed` instead of `delatiled`
```suggestion
The objective of this task is to enhance the "Health Endpoint" for DAB. Currently we only show whether the DAB Engine is healthy or not and which version of DAB is running. However, the objective under this task item is to enhance this to support detailed description of each supported (enabled) endpoint with all different kinds of parameters that would be defined below.

```

2025-01-09 20:16 UTC, RubenCerna2079 commented on docs/design/HealthEndpoint.md
> +| `filter`         | String        | No           | `null`      | Filter condition applied to the health check query (e.g., `"Id eq 1"`).                             |
Why would we need a filter for the health check?

2025-01-09 20:16 UTC, RubenCerna2079 commented on docs/design/HealthEndpoint.md
> +      "threshold-ms": 100 (optional default: 10000)
I think it might be good to show how it would look like when there are multiple `data-source`

2025-01-09 20:16 UTC, RubenCerna2079 commented on docs/design/HealthEndpoint.md
> +  "status": "Healthy",
Why are there 2 status?

2025-01-14 00:13 UTC, Aniruddh25 commented on docs/design/HealthEndpoint.md
> +The runtime configuration would include details like cache-ttl in case we need to cache the response of health checks, the max-drop value which tells you the degree of parallelism i.e. how many queri
```suggestion
The runtime configuration would include details like cache-ttl in case we need to cache the response of health checks, the max-dop value which tells you the degree of parallelism i.e. how many queries that DAB shoud run at once to get health results and roles i.e. which role is allowed to view the health information of DAB.
```

2025-01-14 00:15 UTC, Aniruddh25 commented on docs/design/HealthEndpoint.md
> +| `cache-ttl`   | Integer       | No           | `5`         | Time-to-live (in seconds) for caching health check results.                                          |
mention the unit of sec in the name of the property for eg: `cache-ttl-sec`

2025-01-14 00:18 UTC, Aniruddh25 commented on docs/design/HealthEndpoint.md
> +The idea of using this updates configuration is to allow the developer to influence how the checks work against the datasource/entity. This would provide him with a more detailed process for checking
```suggestion
The idea of using this updates configuration is to allow the developer to influence how the checks work against the datasource/entity. This would provide them with a more detailed process for checking if DAB engine is healthy and would give them an enhanced user experience. 
```
Being more neutral on the use of pronouns.

2025-01-14 00:21 UTC, Aniruddh25 commented
> > How will we be checking if an endpoint is healthy or not? Are we gonna make a db call internally? Or hit the endpoint itself to check the status? Or something else?
> 
> Yes, as mentioned in the document, we would be making the call internally and hitting the specified query. If this query is sucessfull and within the threshold specified, the entity would be considered healthy. Else, we would say, its unhealthy with the exception message

What if the specified query itself has Syntax errors? if the datasource is healthy, we might report a false -ve. how do we plan to validate the query text?

2025-01-14 00:22 UTC, Aniruddh25 commented
Fix the PR description to remove the text from the PR template

2025-01-14 00:22 UTC, Aniruddh25 requested changes
Waiting for addressing the comments

2025-01-15 16:52 UTC, sezal98 commented on docs/design/HealthEndpoint.md
> +| `roles`       | Array         | No           | `*`         | Roles allowed to access the health endpoint (e.g., `anonymous`, `authenticated`).                   |
* would match with all the items in the list. Either authenticated or anonymous

2025-01-15 16:52 UTC, sezal98 commented on docs/design/HealthEndpoint.md
> +      "threshold-ms": 100 (optional default: 10000)
This would be handled later, in another issue.

2025-01-15 16:52 UTC, sezal98 commented on docs/design/HealthEndpoint.md
> +| `filter`         | String        | No           | `null`      | Filter condition applied to the health check query (e.g., `"Id eq 1"`).                             |
Filter is to create a query for entities and execute it that specific filter to get the response time

2025-01-17 07:05 UTC, sezal98 commented
> > > How will we be checking if an endpoint is healthy or not? Are we gonna make a db call internally? Or hit the endpoint itself to check the status? Or something else?
> > 
> > 
> > Yes, as mentioned in the document, we would be making the call internally and hitting the specified query. If this query is sucessfull and within the threshold specified, the entity would be considered healthy. Else, we would say, its unhealthy with the exception message
> 
> What if the specified query itself has Syntax errors? if the datasource is healthy, we might report a false -ve. how do we plan to validate the query text?

Yes, currently we dont have the scenario to validate the query being passed. 
We can include this in the optimizations coming up 
https://github.com/Azure/data-api-builder/issues/2529
Added this in the below issue for tracking

2025-01-17 07:06 UTC, sezal98 commented
/azp run

2025-01-17 09:03 UTC, abhishekkumams commented
> > > > How will we be checking if an endpoint is healthy or not? Are we gonna make a db call internally? Or hit the endpoint itself to check the status? Or something else?
> > > 
> > > 
> > > Yes, as mentioned in the document, we would be making the call internally and hitting the specified query. If this query is sucessfull and within the threshold specified, the entity would be considered healthy. Else, we would say, its unhealthy with the exception message
> > 
> > 
> > What if the specified query itself has Syntax errors? if the datasource is healthy, we might report a false -ve. how do we plan to validate the query text?
> 
> Yes, currently we dont have the scenario to validate the query being passed. We can include this in the optimizations coming up #2529 Added this in the below issue for tracking

I wonder if it's just about checking if the datasource is healthy, why do we need to get query from user, why can't we just run a basic query by ourself, this will simplify the process and remove dependency on user as well as cases where they might provide an invalid query? 

health check should be as light-weight as possible.

2025-01-23 11:20 UTC, sezal98 commented
/azp run

2025-01-29 04:15 UTC, abhishekkumams commented on docs/design/HealthEndpoint.md
> +Here we would carry out standard queries based on the datasource type and execute them under the given threshold. If the engine gets the result below the specified threshold, the DB is considered hea
It would be good to add those standard queries that is being mentioned here.

2025-01-29 04:21 UTC, abhishekkumams commented on docs/design/HealthEndpoint.md
> +      "query": "SELECT TOP 1 1", (Based on DB Type)
i thought we decided to remove this query from here and not allow use to configure.

2025-01-29 04:23 UTC, abhishekkumams commented on docs/design/HealthEndpoint.md
> +  "status": "Unhealthy",/"status": "Healthy",
```suggestion
  "status": "Unhealthy/Healthy",
```

2025-01-29 04:25 UTC, abhishekkumams commented on docs/design/HealthEndpoint.md
> +    "<entity-name>": {
for REST and GRAPHQL will there be separate JSON objects?

2025-01-29 04:26 UTC, abhishekkumams commented on docs/design/HealthEndpoint.md
> ++ We do not support health checks for stored procedures.
I think we are also not supporting hot-reload right? it would be good to add as limitation as well.

2025-01-29 04:29 UTC, abhishekkumams commented on docs/design/HealthEndpoint.md
> +The runtime configuration would include details like cache-ttl in case we need to cache the response of health checks, the max-dop value which tells you the degree of parallelism i.e. how many querie
```suggestion
The runtime configuration would include details like cache-ttl in case we need to cache the response of health checks, the max-dop value which specifies the degree of parallelism i.e. how many queries that DAB should run at once to get health results and roles i.e. which role is allowed to view the health information of DAB.
```

2025-01-29 04:31 UTC, abhishekkumams commented on docs/design/HealthEndpoint.md
> +> Example: If we have a SQL Server, we would execute the standard query given belowe for SQL Server and if the elapsed time for this query is under the threshold, the data source would be considered
```suggestion
> Example: If we have a SQL Server, we would execute the standard query given below for SQL Server and if the elapsed time for this query is under the threshold, the data source would be considered healthy.
```

2025-01-29 04:32 UTC, abhishekkumams commented on docs/design/HealthEndpoint.md
> +For this we run a **POST** query against the base URL **http://localhost:5000/graphl/** with a Request BODY.\
```suggestion
For this we run a **POST** query against the base URL **http://localhost:5000/graphql/** with a Request BODY.\
```

2025-01-29 05:16 UTC, abhishekkumams commented
Can you also add how you'll be testing this feature and what different scenarios are there.
for example:
if global rest is disabled
entity rest is disabled
same for graphql

how does the above scenarios affect the health check output? info about these would be helpful.

2025-01-29 09:58 UTC, sezal98 commented on docs/design/HealthEndpoint.md
> +      "query": "SELECT TOP 1 1", (Based on DB Type)
yes based on DB Type we will take it up

2025-01-29 09:58 UTC, sezal98 commented on docs/design/HealthEndpoint.md
> ++ We do not support health checks for stored procedures.
added

2025-01-29 09:58 UTC, sezal98 commented on docs/design/HealthEndpoint.md
> +    "<entity-name>": {
yes we would have different objects for rest and graphql

2025-01-29 10:45 UTC, sezal98 commented
> Can you also add how you'll be testing this feature and what different scenarios are there. for example: if global rest is disabled entity rest is disabled same for graphql
> 
> how does the above scenarios affect the health check output? info about these would be helpful.

Added Test scenaios

2025-01-29 11:04 UTC, abhishekkumams commented on docs/design/HealthEndpoint.md
> +    * Entity health _ and Entity GraphQL DISABLED : Validation Error in Config
what does `_` means? why validation error in config?

2025-01-29 11:05 UTC, abhishekkumams commented on docs/design/HealthEndpoint.md
> +    * Entity health _ and Entity GraphQL DISABLED : Validation Error in Config
why validation error if graphQL is disabled at entity level?

2025-01-29 16:14 UTC, sezal98 commented on docs/design/HealthEndpoint.md
> +Health Check result scenarios for different cases of Health check and GraphQL and Rest entities enabled or disabled.\
This is needed to insert a new line

2025-01-29 16:15 UTC, sezal98 commented on docs/design/HealthEndpoint.md
> +    * Entity health _ and Entity GraphQL DISABLED : Validation Error in Config
This is the behavior without the healthEndpoint as well. havent modified anything specific related to this

2025-01-29 16:17 UTC, sezal98 commented
/azp run

2025-01-30 04:28 UTC, abhishekkumams commented on docs/design/HealthEndpoint.md
> +    * Entity health _ and Entity GraphQL DISABLED : Validation Error in Config
I verified with the latest stable release and i don't see this case happening.

https://github.com/user-attachments/assets/066b451b-3098-4c64-93ee-57f7da0b2cc0

I also verified with the `dab validate`.
![image](https://github.com/user-attachments/assets/7d7a1f63-b659-4b9e-b639-591d7f1e88e6)


Also, if it's happening, please verify once with the team. It's not the expected behaviour for the health check as I mentioned in the demo as well.

2025-01-30 06:11 UTC, sezal98 commented on docs/design/HealthEndpoint.md
> +    * Entity health _ and Entity GraphQL DISABLED : Validation Error in Config
I have verified on my local in the main branch which has no health changes by putting the global graphQL as enabled and entity graphql for Publishers as disabled. 
I am still seeing the validate issues. Please check 
<img width="740" alt="image" src="https://github.com/user-attachments/assets/e2fa4ae6-d08e-49c0-bf9e-2273e999d8ad" />

Attached the config which I am using as well
Config
```
  "runtime": {
    "rest": {
      "enabled": true,
      "path": "/api",
      "request-body-strict": true
    },
    "graphql": {
      **"enabled": true,**
      "path": "/graphql",
      "allow-introspection": true,
      "multiple-mutations": {
        "create": {
          "enabled": true
        }
      }
    },
    "host": {
      "cors": {
        "origins": [
          "http://localhost:5000"
        ],
        "allow-credentials": false
      },
      "authentication": {
        "provider": "StaticWebApps"
      },
      "mode": "development"
    }
  },
  "entities": {
    "Publisher": {
      "source": {
        "object": "publishers",
        "type": "table"
      },
      "graphql": {
        **"enabled": false,**
        "type": {
          "singular": "Publisher",
          "plural": "Publishers"
        }
      },
      "rest": {
        "enabled": true
      },
```

2025-01-30 06:27 UTC, sezal98 commented on docs/design/HealthEndpoint.md
> +    * Entity health _ and Entity GraphQL DISABLED : Validation Error in Config
I tried the same thing via the latest stable release as well.
 dab validate -c .\dab-config.MsSql.json
Information: Microsoft.DataApiBuilder 1.3.19
<img width="599" alt="image" src="https://github.com/user-attachments/assets/1ea8b6a6-60be-43e9-b02d-061a878f8ad0" />

<img width="636" alt="image" src="https://github.com/user-attachments/assets/41213461-e63c-4a1d-8b22-0f2dea90cf46" />

2025-01-31 05:17 UTC, abhishekkumams commented on docs/design/HealthEndpoint.md
> +    * Entity health _ and Entity GraphQL DISABLED : Validation Error in Config
I see that you see this error happening, but it's not the expected behavior. Instead of documenting it as the expected outcome, we should address the issue itself. The design doc should describe the intended behavior, so that if something doesn't work as expected in the future, we can refer back to it and make the necessary fixes.

2025-01-31 10:18 UTC, sezal98 commented on docs/design/HealthEndpoint.md
> +    * Entity health _ and Entity GraphQL DISABLED : Validation Error in Config
yes I have multiple entries and even after clearing the cache I am seeing the same result as before. If this is not expected then I will debug further as to why its occuring however i have modified the design docuemnt with the expected one

2025-01-31 22:30 UTC, Aniruddh25 commented on docs/design/HealthEndpoint.md
> +The objective of this task is to enhance the "Health Endpoint" for DAB. Currently we only show whether the DAB Engine is healthy or not and which version of DAB is running. However, the objective und
Repetitive text on line 4 - same as line 3.

2025-01-31 22:31 UTC, Aniruddh25 commented on docs/design/HealthEndpoint.md
> +## Objective:
PR description should remove the template description and provide details specific to this PR.

2025-01-31 23:44 UTC, Aniruddh25 commented on docs/design/HealthEndpoint.md
> +Here we would carry out standard queries based on the datasource type and execute them under the given threshold. If the engine gets the result below the specified threshold, the DB is considered hea
Are we no longer letting the health check query to be configured?

2025-01-31 23:45 UTC, Aniruddh25 commented on docs/design/HealthEndpoint.md
> +| `cache-ttl`   | Integer       | No           | `5`         | Time-to-live (in seconds) for caching health check results. If this value is not specified, caching would not be enabled.
can we add the unit of time in the property name? like `cache-ttl-sec`

2025-01-31 23:47 UTC, Aniruddh25 commented on docs/design/HealthEndpoint.md
> +The data source config parameters specify the query that we should run on the data source and the threshold of ms it should come under to qualify as a healthy data source for DAB.
If we removed the query, why does this section still say that the `query` will be specified?

2025-01-31 23:47 UTC, Aniruddh25 commented on docs/design/HealthEndpoint.md
> +The Entity config parameters contain information about the GET filter which needs to be carried out on the data source entity and under what threshold ms should the response be received for it to qua
filter is removed. So, the description should be updated accordingly.

2025-01-31 23:49 UTC, Aniruddh25 commented on docs/design/HealthEndpoint.md
> +| `enabled`     | Boolean       | No           | `false`      | Enables or disables the comprehensive health checks for DAB Engine.                                             |
When this is enabled = false, what do we show on the /health page?

2025-02-02 21:53 UTC, Aniruddh25 commented on docs/design/HealthEndpoint.md
> -      "cache-ttl": 5, (optional default: 5)
What is the `default` if cache-ttl is optional?

2025-02-02 22:07 UTC, Aniruddh25 commented on docs/design/HealthEndpoint.md
> +To form the query we run a for loop against the entities in the config file. For each entity, we add two parameters in the checks array of the output. One for REST and another one for GraphQL, these
if an entity is disabled for `rest`, but its health check is `enabled`  - do we still show the health check results? Same for graphql

If we a role doesn't have `read` permissions on the entity, but its health check is enabled for that role, do we display the health check results for that entity?

2025-02-02 22:10 UTC, Aniruddh25 commented on docs/design/HealthEndpoint.md
> +To execute this query we first need to get the schema of that particular table. Hence for each table we run the `introspection query` to get the schema which gives the column names which are then use
```suggestion
To execute this query we first need to get the schema of that particular entity. Hence for each entity we run the `introspection query` to get the schema which gives the field names which are then used to query the GraphQL endpoint to check the health.
```

2025-02-02 22:12 UTC, Aniruddh25 commented on docs/design/HealthEndpoint.md
> +For this we run a **POST** query against the base URL **http://localhost:5000/graphql/** with a Request BODY.\
what if the base url is different than http://localhost:5000? will this work when dab is running in a docker container?

2025-02-02 22:23 UTC, Aniruddh25 commented on docs/design/HealthEndpoint.md
> +* Global Health Enabled
Good to enlist test scenarios and expectations of when role is specified and entity has read permissions for that role or not.

2025-02-02 22:24 UTC, Aniruddh25 commented on docs/design/HealthEndpoint.md
> +  "query": "query IntrospectionQuery {\n  __schema {\n    queryType {\n      name\n    }\n    mutationType {\n      name\n    }\n    subscriptionType {\n      name\n    }\n    types {\n      ...FullT
would be helpful to see a more readable version of the Introspection query

2025-02-02 22:26 UTC, Aniruddh25 commented on docs/design/HealthEndpoint.md
> +After identifying that specific entity `type` that satisfies the above conditions, we get the object that contains the entity column names. However an entity can have primitive column types or Object
when `field.type.kind` is SCALAR, isnt it NON_NULL as well? If yes. I dont see how these 2 conditions are different. What is the oher value of `field.type.kind` that we will then look for `field.type.ofType.kind`

2025-02-02 22:27 UTC, Aniruddh25 requested changes
Question on what the expected behavior should be when there are conflicting role specifications for an entity..

2025-02-06 14:06 UTC, sezal98 commented on docs/design/HealthEndpoint.md
> +To form the query we run a for loop against the entities in the config file. For each entity, we add two parameters in the checks array of the output. One for REST and another one for GraphQL, these
entity is disabled for rest, but its health check is enabled 
We would show an error in the comprehensive health check saying "Unhealthy" with the exception message saying "Entity is disabled in Config"

 role doesn't have read permissions on the entity, but its health check is enabled for that role
We would show an error in the comprehensive health check saying "Unhealthy" with the exception message saying "Role is not permitted to perform the SELECT query".

2025-02-06 14:06 UTC, sezal98 commented on docs/design/HealthEndpoint.md
> +For this we run a **POST** query against the base URL **http://localhost:5000/graphql/** with a Request BODY.\
For the current case, I have focused on keeping URL as this. Will open an issue to track in case URL is different

2025-02-06 14:06 UTC, sezal98 commented on docs/design/HealthEndpoint.md
> +* Global Health Enabled
added another test scenario on roles

2025-02-06 15:08 UTC, sezal98 commented on docs/design/HealthEndpoint.md
> -      "cache-ttl": 5, (optional default: 5)
Default would is null currently. But after caching is implemented it would be 5 sec

2025-02-06 20:11 UTC, Aniruddh25 commented on docs/design/HealthEndpoint.md
> +The objective of this task is to enhance the "Health Endpoint" for DAB. Currently we only show whether the DAB Engine is healthy or not and which version of DAB is running. However, the objective und
I still the repeated lines. Were they really removed? Perhaps only in your local copy?
Please push your changes to the remote before marking the comment as resolved. Unresolving the conversation for now.

2025-02-06 20:14 UTC, Aniruddh25 commented on docs/design/HealthEndpoint.md
> +| `enabled`     | Boolean       | No           | `false`      | Enables or disables the comprehensive health checks for DAB Engine.                                             |
So, what is shown on this `/health` page in the current way? 

Also, what if someone has an entity named `/health` - wont enabling the new endpoint conflict to that entity's page? What do we do if there is such a conflict?

2025-02-06 20:17 UTC, Aniruddh25 commented on docs/design/HealthEndpoint.md
> +The Entity config parameters contain information about the GET filter which needs to be carried out on the data source entity and under what threshold ms should the response be received for it to qua
Again, I don't see the update in the latest iteration. I cannot sign off unless I see it here.

2025-02-06 20:19 UTC, Aniruddh25 commented on docs/design/HealthEndpoint.md
> +To form the query we run a for loop against the entities in the config file. For each entity, we add two parameters in the checks array of the output. One for REST and another one for GraphQL, these
`Role is not permitted to perform the SELECT query` --> `Role is not permitted to perform the read operation.`

Please confirm this behavior and the respective error message with @JerryNixon

2025-02-06 20:21 UTC, Aniruddh25 commented on docs/design/HealthEndpoint.md
> +For this we run a **POST** query against the base URL **http://localhost:5000/graphql/** with a Request BODY.\
Can't you determine the base url in code without hardcoding localhost?

2025-02-06 20:26 UTC, Aniruddh25 commented on docs/design/HealthEndpoint.md
> +After identifying that specific entity `type` that satisfies the above conditions, we get the object that contains the entity column names. However an entity can have primitive column types or Object
Maybe my question isn't clear.. 

Wouldn't the condition field.type.kind is NON_NULL be true when field.type.kind is SCALAR?

Is your logic to check for Case 2 only when Case 1 is FALSE?

2025-02-06 20:27 UTC, Aniruddh25 requested changes
Still waiting for the resolved comments to show up in the remote.

2025-02-06 21:23 UTC, sezal98 commented on docs/design/HealthEndpoint.md
> +After identifying that specific entity `type` that satisfies the above conditions, we get the object that contains the entity column names. However an entity can have primitive column types or Object
yes in the if condition, the case 1 is checked first. Only when case 1 is false, the other case 2 is checked. 
In case case 1 is positive, Having and OR condition would make the if condition true without evaluation case 2.

Also let me elaborate, Having type.kind as NON_NULL is not alone a valid scenario. Along with this, it needs to have type.ofType.kind as SCALAR as well. Only then case 2 is considered positive.

2025-02-06 21:24 UTC, sezal98 commented
> Question on what the expected behavior should be when there are conflicting role specifications for an entity..

Yes i have added this in the doc

2025-02-06 21:24 UTC, sezal98 commented
> Still waiting for the resolved comments to show up in the remote.

yes i was working on them. Now i have pushed it

2025-02-06 21:26 UTC, sezal98 commented on docs/design/HealthEndpoint.md
> +| `enabled`     | Boolean       | No           | `false`      | Enables or disables the comprehensive health checks for DAB Engine.                                             |
We didnt discuss this in the design discussion. Let me put this question to Jerry.
@JerryNixon Please share your thoughts.

2025-02-06 21:33 UTC, sezal98 commented on docs/design/HealthEndpoint.md
> +The Entity config parameters contain information about the GET filter which needs to be carried out on the data source entity and under what threshold ms should the response be received for it to qua
<img width="591" alt="image" src="https://github.com/user-attachments/assets/e362dacc-245f-4fc1-9671-1eddd2b8611f" />
The changes are already updated. 
<img width="689" alt="image" src="https://github.com/user-attachments/assets/b9873f1b-404d-4e57-922f-997994d9841e" />

2025-02-06 21:36 UTC, sezal98 commented on docs/design/HealthEndpoint.md
> +The objective of this task is to enhance the "Health Endpoint" for DAB. Currently we only show whether the DAB Engine is healthy or not and which version of DAB is running. However, the objective und
Please check the latest commit. It is corrected
<img width="892" alt="image" src="https://github.com/user-attachments/assets/7c4087ee-fca2-4725-9f46-ba06bd3771e4" />

2025-02-06 21:41 UTC, sezal98 commented on docs/design/HealthEndpoint.md
> +To form the query we run a for loop against the entities in the config file. For each entity, we add two parameters in the checks array of the output. One for REST and another one for GraphQL, these
If you see the test scenarios section. I have written the second part only with read operation not SELECT query

2025-02-06 21:42 UTC, sezal98 commented on docs/design/HealthEndpoint.md
> +To form the query we run a for loop against the entities in the config file. For each entity, we add two parameters in the checks array of the output. One for REST and another one for GraphQL, these
I discussed it with the team and Jerry on call.  
@JerryNixon , Please confirm if this is the expected behavior

2025-02-06 22:20 UTC, sezal98 commented on docs/design/HealthEndpoint.md
> +For this we run a **POST** query against the base URL **http://localhost:5000/graphql/** with a Request BODY.\
Can you suggest some way

2025-02-06 23:41 UTC, Aniruddh25 commented on docs/design/HealthEndpoint.md
> +The database type in the data source health config determine the threshold of ms it should come under to qualify as a healthy data source for DAB. We get the database type from the runtime parameters
```suggestion
The database type in the data source health config determines the query that we should run on the data source. The time to run this query should come under the user specified threshold of ms to qualify as a healthy data source for DAB. We get the database type from the runtime parameters to get the query to run on the specific DB Type.
```

2025-02-06 23:44 UTC, Aniruddh25 commented on docs/design/HealthEndpoint.md
> +| `name`         | Array of String        | No (Yes in case of multiple data source)           | Database Type      | Identifier for the data source; useful when multiple data sources exist.
is the name really an Array of string?

2025-02-06 23:49 UTC, Aniruddh25 commented on docs/media/introspection-query.graphql
> +  }
```suggestion
  }
  
```

2025-02-06 23:50 UTC, Aniruddh25 commented on docs/media/introspection-query.graphql
> +      subscriptionType { name }
we dont support subscriptionType yet, do we really need to add it to the introspection?

2025-02-06 23:53 UTC, Aniruddh25 commented on docs/media/introspection-query.graphql
> +      ofType {
Any idea why the 3 nested child levels for ofType?

2025-02-07 01:19 UTC, Aniruddh25 commented on docs/design/HealthEndpoint.md
> +We take the base URL which is and append the REST path in the suffix. After this we get baseUrl/api. (Default Rest Path: /api)\
```suggestion
We take the base URL and append the REST path in the suffix. After this we get baseUrl/api. (Default Rest Path: /api)\
```

2025-02-07 01:30 UTC, Aniruddh25 commented on docs/design/HealthEndpoint.md
> +We add all those column names which satisfies either of these two conditions to the top `columnNames` array and finally use this to create the graphQL query.
```suggestion
We add all those column names which satisfy either of these two conditions to the top `columnNames` array and finally use this to create the graphQL query.
```

2025-02-07 01:37 UTC, Aniruddh25 commented on docs/design/HealthEndpoint.md
> +    * Entity health _ and Entity GraphQL DISABLED : GraphQL Health check shows `status: Unhealthy` and `exception: Health could not be check for this entity as it is disabled in config`.
```suggestion
    * Entity health _ and Entity GraphQL DISABLED : GraphQL Health check shows `status: Unhealthy` and `exception: Health could not be checked for this entity as it is disabled in config`. 
```

2025-02-07 01:38 UTC, Aniruddh25 commented on docs/design/HealthEndpoint.md
> +  * Runtime Health check parameter, `runtime.health.roles` contains "UserRole". However entity permissions doesn't have read permissions on this entity
```suggestion
  * Runtime Health check parameter, `runtime.health.roles` contains "UserRole". However, the `UserRole` doesn't have read permissions on this entity.
```

2025-02-07 01:48 UTC, Aniruddh25 commented on docs/design/HealthEndpoint.md
> +For this we run a **POST** query against the base URL **http://localhost:5000/graphql/** with a Request BODY.\
The httpContext request to the health endpoint should have the compelete url from which you can derive the base url..

See this code in the repo:
   `string path = UriHelper.GetEncodedUrl(httpContext!.Request).Split('?')[0];`

2025-02-07 01:53 UTC, Aniruddh25 requested changes
Overall looks in much better shape. Left few nits. 

But waiting for you getting the clarification on what happens if `/health` conflicts with existing entity name in the config

2025-02-07 09:34 UTC, sezal98 commented on docs/design/HealthEndpoint.md
> +| `name`         | Array of String        | No (Yes in case of multiple data source)           | Database Type      | Identifier for the data source; useful when multiple data sources exist.
yes this field would be elaborated once we consider the case of multiple data sources. Hence array. Else it would not be needed as db type is taken

2025-02-07 09:34 UTC, sezal98 commented on docs/media/introspection-query.graphql
> +      subscriptionType { name }
This is the sample query that i picked from library. Havent modified it 
Please suggest if there is some other way to create this

2025-02-07 09:34 UTC, sezal98 commented on docs/media/introspection-query.graphql
> +      ofType {
not sure. Would need to deepdive into understanding graphql and get back on this. 
I picked this up from the links above

2025-02-07 09:34 UTC, sezal98 commented on docs/media/introspection-query.graphql
> +  }
why do we need an extra line?

2025-02-07 21:30 UTC, JerryNixon requested changes
@Aniruddh25

2025-02-07 21:30 UTC, JerryNixon commented on docs/design/HealthEndpoint.md
> +```
I am not sure I understand. Do you really use CURL for this check?

2025-02-07 21:30 UTC, JerryNixon commented on docs/design/HealthEndpoint.md
> +```
Errors: 

1. "dab-configuration" is just "configuration"
2. checks is an array of objects, not an object of objects
3. "responseTimeMs" is "duraction-ms"
4. "maxallowedresponsetimems" is "threshold-ms"

2025-02-07 21:30 UTC, JerryNixon commented on docs/design/HealthEndpoint.md
> +    * Health for this entity is displayed with `status: Unhealthy` and `exception: Health could not be checked for this entity as it does not have permissions to perform read operation`.
I believe it would better to allow for a 30x http status to be returned and react to that. This makes it so you do not have to look up entity permissions, you call every entity and simply handle them all the same. This enforces permissions without requiring the health check to look them up - which seems far more ideal.

2025-02-07 21:30 UTC, JerryNixon commented on docs/design/HealthEndpoint.md
> +There is no official industry standard for the health endpoint. /health or variations like /_health are common by convention.\
Could you more clearly state that this feature will have two endpoints? / and /health. That / (the root) returns what it already returns today, the basic health) and that /health returns the more comprehensive health depending on a mixture of if health is enabled and the user meets the roles requirement?

2025-02-07 21:30 UTC, JerryNixon commented on docs/design/HealthEndpoint.md
> +## Code Details
It's almost like there are two documents here, each repeating the other when they should be mixed together so you do not repeat yourself so much - this will lead us to get details out of sync.

2025-02-07 21:30 UTC, JerryNixon commented on docs/design/HealthEndpoint.md
> +**Introspection Query Filter**
Why are you not using the metadata of the entity to build this? The GraphQL schema is built from the entity metadata and you already have the entity metadata, wouldn't that save you this costly step?

2025-02-07 21:30 UTC, JerryNixon commented on docs/design/HealthEndpoint.md
> ++ Condition 2: If the `field.type.kind` is `NON_NULL` then check if `field.type.ofType.kind` is `SCALAR`.
All of these rules would not be necessary if you used the entity metadata to infer the GraphQL query instead of using introspection. This feels needlessly complex and brittle. Since you already have the entity metadata and since we know the GraphQL schema is built from the metadata, you should be able to more efficiently infer the GraphQL query from the metadata than rely on this process and bag of extra rules you are listing here.

2025-02-07 21:30 UTC, JerryNixon commented on docs/design/HealthEndpoint.md
> +```
This would be easier to read a C#:

```csharp
using System.Text.Json;
using System.Net.Http;
using System.Diagnostics;
using System.Threading;

var queryText = "{UserTable(first: 4) {items { content id }}}";

async Task<TimeSpan> ExecuteAsync(string query, CancellationToken cancellationToken = default)
{
    var httpClient = new HttpClient();
    var queryUrl = "baseUrl/graphql";

    var queryObject = new { query = query };
    var queryJson = JsonSerializer.Serialize(queryObject);
    var queryContent = new StringContent(queryJson, System.Text.Encoding.UTF8, "application/json");

    var stopwatch = new Stopwatch();

    stopwatch.Start();
    var responseObject = await httpClient.PostAsync(queryUrl, queryContent, cancellationToken);
    stopwatch.Stop();
    
    responseObject.EnsureSuccessStatusCode();
    var responseText= await responseObject.Content.ReadAsStringAsync();
    var responseJson = JsonDocument.Parse(responseText);

    return TimeSpan.FromMilliseconds(stopwatch.ElapsedMilliseconds);
}
```

2025-02-07 21:30 UTC, JerryNixon commented on docs/design/HealthEndpoint.md
> ++ Hot-Reload is not supported in Comprehensive Health Endpoint.
Why?

2025-02-07 21:30 UTC, JerryNixon commented on docs/design/HealthEndpoint.md
> ++ Multiple data-source configs are not supported in the HealthCheck Report
What!? Why? This may have been true when we were shooting for v1.4, but now that we are in 1.5, we have time to do this right.

2025-02-07 21:30 UTC, JerryNixon commented on docs/media/introspection-query.graphql
> +      subscriptionType { name }
I still think introspection is not the best approach.

2025-02-07 21:33 UTC, JerryNixon commented on docs/design/HealthEndpoint.md
> +| `name`         | Array of String        | No (Yes in case of multiple data source)           | Database Type      | Identifier for the data source; useful when multiple data sources exist.
By the way, we DO support multiple data sources.

2025-02-07 21:36 UTC, JerryNixon commented on docs/design/HealthEndpoint.md
> ++ First is to check the roles present in the `runtime.health.roles` array in the config. We check if the incoming user has access to the comprehensive health check report i.e. they are in this array
It is strange that you discuss the same thing in two places - seems risky to get out of sync.

2025-02-10 16:43 UTC, sezal98 commented on docs/design/HealthEndpoint.md
> +## Code Details
There are two sections in the document. 
First one is referring to the config changes which includes runtime, data-source and entities.
Second section includes the code details about how these above config parameters are being used to calculate the health config.

2025-02-10 16:43 UTC, sezal98 commented on docs/design/HealthEndpoint.md
> +We focus on two aspects in terms of roles for health report.
The concept of runtime mode has not been discussed yet. Lets not make changes suddenly without discussing it in detail. We can connect over a call once, after which I am happy to incorporate this

2025-02-10 16:43 UTC, sezal98 commented on docs/design/HealthEndpoint.md
> ++ First is to check the roles present in the `runtime.health.roles` array in the config. We check if the incoming user has access to the comprehensive health check report i.e. they are in this array
First section is 'what options the user can input' and second is after the user input 'how we interpret it and use it to calculate health'. 

Will include this role dependence on runtime after discussion.

2025-02-10 16:43 UTC, sezal98 commented on docs/design/HealthEndpoint.md
> +#### Rest Query
yes that is correct.  Please take the test scenarios below

2025-02-10 16:43 UTC, sezal98 commented on docs/design/HealthEndpoint.md
> +#### GraphQL Query
yes that is correct. Please take the test scenarios below

2025-02-10 16:43 UTC, sezal98 commented on docs/design/HealthEndpoint.md
> +```
yes i use this to get column Information.

2025-02-10 16:43 UTC, sezal98 commented on docs/design/HealthEndpoint.md
> +**Introspection Query Filter**
Not sure if I understand you correctly. Lets discuss on call

2025-02-10 16:43 UTC, sezal98 commented on docs/design/HealthEndpoint.md
> ++ Condition 2: If the `field.type.kind` is `NON_NULL` then check if `field.type.ofType.kind` is `SCALAR`.
Duplicate comment

2025-02-10 16:43 UTC, sezal98 commented on docs/design/HealthEndpoint.md
> +```
I am unable to understand why we would include code details in the design doc. CURL command gives all the information the coder would need to create the above snippet. 
Can you elaborate why you feel this is required?

2025-02-10 16:43 UTC, sezal98 commented on docs/design/HealthEndpoint.md
> +```
1. Modified
2. Modified
3 and 4. Is this recently changed?
<img width="293" alt="image" src="https://github.com/user-attachments/assets/8e2d2bb8-8685-4756-8773-009ce40c9cc6" />

2025-02-10 16:43 UTC, sezal98 commented on docs/design/HealthEndpoint.md
> ++ Multiple data-source configs are not supported in the HealthCheck Report
We have a separate issue to track this. If we get time, we can include this in 1.5. Have a separate PR to add the details about multiple data sources later in the design document

2025-02-17 11:21 UTC, sezal98 commented on docs/design/HealthEndpoint.md
> +We focus on two aspects in terms of roles for health report.
incorporated

2025-02-17 11:21 UTC, sezal98 commented on docs/design/HealthEndpoint.md
> ++ Hot-Reload is not supported in Comprehensive Health Endpoint.
This needs to investigated further. Already tracking it

2025-02-17 11:21 UTC, sezal98 commented on docs/design/HealthEndpoint.md
> +To form the query we run a for loop against the entities in the config file. For each entity, we add two parameters in the checks array of the output. One for REST and another one for GraphQL, these
updated as per new

2025-02-17 11:21 UTC, sezal98 commented on docs/media/introspection-query.graphql
> +      subscriptionType { name }
Updated the approach

2025-02-17 11:28 UTC, sezal98 commented on docs/design/HealthEndpoint.md
> +| `roles`       | Array of strings         | Yes           | NA         | Roles allowed to access the health endpoint (e.g., `anonymous`, `authenticated`).                   |
Added

2025-02-17 11:28 UTC, sezal98 commented on docs/design/HealthEndpoint.md
> +| `enabled`     | Boolean       | No           | `false`      | Enables or disables the comprehensive health checks for DAB Engine. In case of disabled; we show the previous format of health check.
updated

2025-02-17 11:30 UTC, sezal98 commented on docs/design/HealthEndpoint.md
> +For this we run a **POST** query against the base URL **http://localhost:5000/graphql/** with a Request BODY.\
done

2025-02-17 11:30 UTC, sezal98 commented on docs/design/HealthEndpoint.md
> +**Introspection Query Filter**
done

2025-02-17 11:39 UTC, sezal98 commented
/azp run

2025-02-18 04:47 UTC, abhishekkumams approved these changes
LGTM, thanks for updating.

2025-02-18 05:35 UTC, sezal98 commented
/azp run

2025-02-18 07:32 UTC, sezal98 commented
/azp run

2025-02-19 04:39 UTC, JerryNixon requested changes

2025-02-19 04:39 UTC, JerryNixon commented on docs/design/HealthEndpoint.md
> +| `cache-ttl-seconds`   | Integer       | No           | `5`         | Time-to-live (in seconds) for caching health check results. **If this value is not specified or is 0, caching would not be enabl
> Currently, caching is not implemented hence, value is considered to be null.

This is unclear, it makes it sound like caching is not going to be part of the solution when it is. If you are not planning to implement caching, please let me know.

2025-02-19 04:39 UTC, JerryNixon commented on docs/design/HealthEndpoint.md
> +| `roles`       | Array of strings         | <table><tr><th>Environment</th><th>Required</th></tr><tr><td>Development</td><td>No</td></tr><tr><td>Production</td><td>Yes</td></tr></table>   | <table><
nit: customer-role > custom-role

2025-02-19 04:39 UTC, JerryNixon commented on docs/design/HealthEndpoint.md
> +The database type in the data source health config determines the query that we should run on the data source. The time to run this query should come under the user specified threshold_ms to qualify
nit: threshold_ms > threshold-ms

2025-02-19 04:39 UTC, JerryNixon commented on docs/design/HealthEndpoint.md
> +**This check opens a connection to the data source and validates the connection string and network access. Further it runs a simple query to validate user permissions and responsiveness or the DB.**
nit: responsiveness or the DB > responsiveness for the DB

2025-02-19 04:39 UTC, JerryNixon commented on docs/design/HealthEndpoint.md
> +The Entity config parameters contain information about the `first` which defines the number of first rows to be returned when executing a READ operation on the data source entity and under what thres
nit: parameters > settings
nit: defines the number of first rows > defines the number of rows
nit: under what threshold ms should the response be received > under what threshold the response should be received

2025-02-19 04:39 UTC, JerryNixon commented on docs/design/HealthEndpoint.md
> +| `threshold-ms`   | Integer       | No           | `10000`     | Threshold in milliseconds for the query response time before the check is considered degraded. Minimum : 1 Maximum: INT_MAX. Zero is
> considered degraded

We are not using the health status `degraded` just `healthy` and `unhealthy`.

2025-02-19 04:39 UTC, JerryNixon commented on docs/design/HealthEndpoint.md
> +> For data source health check we only need to check health report access but for entities (rest and graphql) we run both health report access and read permissions access.
Unclear. Will this be true for Health Checks or only Static Web Apps?

2025-02-19 04:39 UTC, JerryNixon commented on docs/design/HealthEndpoint.md
> +**Access to comprehensive health report is measured via the `runtime.health.roles` array where `anonymous` is added to allow unauthenticated access to an entity, `authenticated` is added to allow all
nit: custome-role > custom-role

2025-02-19 04:39 UTC, JerryNixon commented on docs/design/HealthEndpoint.md
> +The Health Report also contains a section for the configuration summary for the health checks. It provides information about various parameters being enabled or disabled on the global runtime scale.
nit: parameters > settings

2025-02-19 04:39 UTC, JerryNixon commented on docs/design/HealthEndpoint.md
> +The Health Report also contains a section for the configuration summary for the health checks. It provides information about various parameters being enabled or disabled on the global runtime scale.
> global runtime scale

Scale? Not sure what that is supposed to mean.

2025-02-19 04:39 UTC, JerryNixon commented on docs/design/HealthEndpoint.md
> +DAB Config has two parameters in the `data-source.health` config section. (Enabled and threshold_ms)\
nit: two parameters > two settings

Just a reminder, a `parameter` is a variable listed in a method’s signature, used to pass data into the method.

2025-02-19 04:39 UTC, JerryNixon commented on docs/design/HealthEndpoint.md
> +DAB Config has two parameters in the `data-source.health` config section. (Enabled and threshold_ms)\
nit: threshold_ms > threshold-ms

2025-02-19 04:39 UTC, JerryNixon commented on docs/design/HealthEndpoint.md
> +      "tags": ["database"],
We will also add `database-type` as a tag.

2025-02-19 16:30 UTC, sezal98 commented on docs/design/HealthEndpoint.md
> +| `cache-ttl-seconds`   | Integer       | No           | `5`         | Time-to-live (in seconds) for caching health check results. **If this value is not specified or is 0, caching would not be enabl
Will be done subsequently. Not in current design scope.

2025-02-19 16:39 UTC, sezal98 commented on docs/design/HealthEndpoint.md
> +Finally we add the query parameter which is the first 'x' values to get the final query as **`<baseUrl>/<runtime.rest.path>/<entity-name>.rest.path?$first=x`**.
Here it would be a parameter itself as I am refering to query parameters not config

2025-02-19 16:39 UTC, sezal98 commented on docs/design/HealthEndpoint.md
> +query = $"{{{entityName.ToLowerInvariant()}(first: {First}) {{items {{ {string.Join(" ", columnNames)} }}}}}}"
yes, this works

2025-02-19 16:41 UTC, sezal98 commented
/azp run

2025-02-19 22:54 UTC, Aniruddh25 commented on docs/design/HealthEndpoint.md
> +![Class Diagram](dataSourceHealthCheckTestScenarioFlowchart.png)
Thank you for adding these diagrams! Helps get an overall idea of the different conditions! 💯

2025-02-19 23:47 UTC, Aniruddh25 commented on docs/design/HealthEndpoint.md
> +This is the superset of all roles. The anonymous system role is assigned to requests executed by unauthenticated users. Runtime configuration defined entities must include permissions for the anonymo
technically anonymous is not "superset" since an authenticated request is not anonymous. If an entity has read permission granted to authenticated only, then anonymous cant perform read. In that sense, anonymous is not superset.

2025-02-19 23:49 UTC, Aniruddh25 commented on docs/design/HealthEndpoint.md
> +> Example: In Static Web Apps, a user is a member of the anonymous role by default. If the user is authenticated, the user is a member of both the anonymous and authenticated roles. If the client app
the user may be a member of both the roles - anonymous and authenticated. But, I think we evaluate the request in the context of `authenticated` role only.

2025-02-20 00:04 UTC, Aniruddh25 commented on docs/design/HealthEndpoint.md
> +| -          | ≥ 1          | `Unhealthy`      |
For any reason if an entity check is **skipped**, because rest is disable or graphql is disabled or role doesn't have permission, what do we consider it as being Healthy or Unhealthy for the overall health calculation? i.e. would something being skipped make the overall status - unhealthy?

2025-02-20 00:05 UTC, Aniruddh25 approved these changes
This has come a long way! Thank you for your patience in addressing all the comments. 

Left a few comments to answer but other than that looks good to merge.

2025-02-21 08:13 UTC, sezal98 commented on docs/design/HealthEndpoint.md
> +This is the superset of all roles. The anonymous system role is assigned to requests executed by unauthenticated users. Runtime configuration defined entities must include permissions for the anonymo
Superset would mean that if permission is granted to the parent its accessible to all children. But it doesnt mean that if permission is granted to child, then it flows to parent. 
Superset here is reffered as if health has roles array. And if this roles array has anonymous role, then everyone can access it. We need not check again more. 
Updated to more clear

2025-02-21 08:13 UTC, sezal98 commented on docs/design/HealthEndpoint.md
> +> Example: In Static Web Apps, a user is a member of the anonymous role by default. If the user is authenticated, the user is a member of both the anonymous and authenticated roles. If the client app
yes that is correct. Added specific text for this

2025-02-21 08:13 UTC, sezal98 commented on docs/design/HealthEndpoint.md
> +| -          | ≥ 1          | `Unhealthy`      |
if the entity check is skipped it is not counted towards the overall health status calculation. Its ignored

2025-02-21 08:14 UTC, sezal98 commented
/azp run

2025-02-24 04:29 UTC, sezal98 commented
/azp run

2025-02-24 07:36 UTC, sezal98 commented
/azp run

2025-02-24 08:02 UTC, merged